apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task-service
  namespace: app
  labels:
    release: kube-prom       # Must match Prometheus's serviceMonitorSelector
spec:
  selector:
    matchLabels:
      app: task-service
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
